---
repos:
  - repo: local
    hooks:
      - id: check-file-structure
        name: Check File Structure
        entry: python3 -m scripts.pre_commit_check
        language: system
        types: [file]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=102400"]
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
    - id: hadolint
      name: Hadolint Dockerfile Linter
      entry: docker run --rm -v ${PWD}:/mnt hadolint/hadolint hadolint
      language: system
      types: [dockerfile]
      files: ^Dockerfile$
  - repo: local
    hooks:
      - id: docker-compose-lint
        name: Docker Compose Linter (dclint)
        entry: docker run -t --rm -v ${PWD}:/app zavoloklom/dclint .
        language: system
        types: [yaml]
        files: ^docker-compose\.ya?ml$
      