services:
  project-z:
    image: "digikwal/project-z:latest"
    env_file:
      - .env
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
      - 27015:27015/tcp
    volumes:
      - data:/home/Zomboid
      - workshop:/opt/pzserver/steamapps/workshop

volumes:
  data:
  workshop:
