name: Build and Push

on:
  workflow_run:
    workflows:
      - Semantic release
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download release metadata
        uses: actions/download-artifact@v4
        with:
          name: release-metadata
          path: ./artifacts/release-metadata
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: digikwal/project-z
          run-id: ${{ github.event.workflow_run.id }}

      - name: Load release metadata
        run: |
          if [[ ! -f ./artifacts/release-metadata/release_tag.txt ]]; then
            echo "Error: release_tag.txt not found!" >&2
            exit 1
          fi
          RELEASE_TAG=$(cat ./artifacts/release-metadata/release_tag.txt)
          if [[ -z "$RELEASE_TAG" ]]; then
            echo "Error: RELEASE_TAG is empty!" >&2
            exit 1
          fi
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            --tag digikwal/project-z:${{ env.RELEASE_TAG }} \
            --file docker/Dockerfile .

      - name: Push Docker image and tags
        run: |
          docker push digikwal/project-z:${{ env.RELEASE_TAG }}
          if [[ "${{ env.RELEASE_TAG }}" != *"-"* ]]; then
            docker tag digikwal/project-z:${{ env.RELEASE_TAG }} digikwal/project-z:latest
            docker push digikwal/project-z:latest
          else
            docker tag digikwal/project-z:${{ env.RELEASE_TAG }} digikwal/project-z:dev
            docker push digikwal/project-z:dev
          fi