name: Semantic release

on:
  workflow_run:
    workflows:
      - Pre-commit
    types:
      - completed

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release notes and version
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=$(npx semantic-release | tee /dev/stderr | grep -oP '(?<=next release version is )[^ ]+')
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

      - name: Save release metadata
        run: |
          # Save metadata to files
          if [[ -z "${RELEASE_TAG}" ]]; then
            echo "Error: RELEASE_TAG is empty!" >&2
            exit 1
          fi
          echo "${RELEASE_TAG}" > release_tag.txt

      - name: Upload release metadata
        uses: actions/upload-artifact@v4
        with:
          name: release-metadata
          path: |
            release_tag.txt
